<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GenericServices.StatusGeneric" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
    <PackageReference Include="Minio" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentLifeHelper.Common\StudentLifeHelper.Common.csproj" />
    <ProjectReference Include="..\StudentLifeHelper.Data\StudentLifeHelper.Data.csproj" />
  </ItemGroup>

</Project>
